# config/settings.py

STOCK_SYMBOLS = [
    "AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "TSLA", "AMD", "NFLX", "INTC",
    "JPM", "BAC", "GS", "V", "MA", "DIS", "WMT", "COST", "HD", "MCD",
    "KO", "PEP", "XOM", "CVX", "PFE", "JNJ", "MRK", "UNH", "ABBV", "TMO",
    "ORCL", "CRM", "ADBE", "CSCO", "QCOM", "AVGO", "TXN", "IBM", "SHOP", "UBER",
    "PLTR", "SNOW", "SQ", "PYPL", "PANW", "CRWD", "NET", "DDOG", "MU", "LULU",
    "SPY", "QQQ", "IWM", "DIA", "XLF", "XLK", "XLE", "XLV", "XLY", "XLP"
]

CRYPTO_SYMBOLS = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "XRP/USDT", "ADA/USDT"
]

ALL_SYMBOLS = STOCK_SYMBOLS
ALL_CRYPTO_SYMBOLS = CRYPTO_SYMBOLS

INITIAL_CAPITAL = 100000.0
DATA_PERIOD = "180d"
DATA_INTERVAL = "1h"

RESULTS_DB = "results.db"
# Database limits
MAX_ROWS_PER_SYMBOL = 200
MAX_TOTAL_ROWS = 20000
TOP_N_STRATEGIES = 20

MIN_SHARPE = 1.25
MIN_TOTAL_RETURN = 0.03
MAX_ACCEPTABLE_DRAWDOWN = -0.12
MIN_TRADES = 12

PAPER_TRADE_SYMBOL_LIMIT = 5
PAPER_TRADE_MAX_ALLOCATION_PER_POSITION = 0.10
PAPER_TRADE_MIN_SHARPE = 1.5
PAPER_TRADE_MAX_DRAWDOWN = -0.10
PAPER_TRADE_MIN_RETURN = 0.05

# Portfolio / risk
MAX_POSITIONS = 8
MAX_TOTAL_EXPOSURE = 0.60          # 60% of equity
MAX_POSITION_PCT = 0.10            # 10% per position
MAX_DAILY_LOSS_PCT = 0.03          # 3% daily stop
MAX_ORDERS_PER_CYCLE = 3
MAX_SYMBOL_REENTRIES_PER_DAY = 1

# Connection defaults
DEFAULT_BROKER_ACCOUNT = "alpaca_paper"
DEFAULT_CRYPTO_ACCOUNT = "binance_paper"

# Simple sector map for exposure control
SECTOR_MAP = {
    "AAPL": "TECH", "MSFT": "TECH", "NVDA": "TECH", "AMD": "TECH", "AVGO": "TECH",
    "GOOGL": "TECH", "META": "TECH", "ORCL": "TECH", "CSCO": "TECH", "QCOM": "TECH",
    "XLF": "FINANCIALS", "JPM": "FINANCIALS", "BAC": "FINANCIALS", "GS": "FINANCIALS",
    "XLE": "ENERGY", "XOM": "ENERGY", "CVX": "ENERGY",
    "XLV": "HEALTHCARE", "PFE": "HEALTHCARE", "JNJ": "HEALTHCARE", "MRK": "HEALTHCARE", "ABBV": "HEALTHCARE",
}
MAX_SECTOR_EXPOSURE = 0.25